-- Solicitação Cerconi via sala 3 

SELECT BIANO.NRO_ACORDO ACORDO, BIANO.CODESPECIE, BIANO.NRO_EMPRESA LOJA, BIANO.FORNECEDOR, TO_CHAR(BIANO.DATA_EMISSAO, 'DD/MM/YYYY') EMISSAO, BIANO.VLR_ACORDO TOTAL_ACORDO, 
BIANO.VLR_PAGO_FIN PAGO, (BIANO.VLR_ACORDO - NVL(BIANO.VLR_PAGO_FIN,0)) EM_ABERTO, BIANO.STATUS
FROM CONSINCO.NAGV_TAE_ACORDOS_V4 BIANO
WHERE BIANO.DATA_EMISSAO BETWEEN :DT1 AND :DT2
AND (:LS1 IS NULL OR BIANO.CODESPECIE = :LS1)
AND BIANO.STATUS = 'Envelope finalizado' 
