-- Solicitação Cerconi, Teams

SELECT T.EMP, TO_CHAR(T.DTA_ENTRADA, 'DD/MM/YYYY') DTA_ENTRADA,
NVL(C.NUMERONF, T.NUMERONF) NUMERONF, T.CODESPECIE,
T.SEQPESSOA || ' - ' || G.NOMERAZAO FORNEC,
CASE WHEN T.CODESPECIE IN ('CONTLG', 'ACRLOG') THEN 0 ELSE T.VLR_TOTAL END VLR_TOTAL,
NVL(NULLIF(C.PERC_FID, 0), T.PERCDESCCONTRATO) PERC_FID,
NVL(NULLIF(C.VLR_FIDELIDADE, 0), T.VLRDESCCONTRATO) VLR_FIDELIDADE,
NVL(C.PERC_LOG, 0) PERC_LOG,
CASE WHEN T.CODESPECIE IN ('CONTLG', 'ACRLOG') THEN T.VLR_TOTAL ELSE NVL(C.VLR_LOGISTICO, 0) END VLR_LOGISTICO,
O.FORMA_PAGAMENTO,
TO_CHAR(O.DTA_OPERACAO, 'DD/MM/YYYY') DTA_OPERACAO,
O.VLROPERACAO,
O.OBSERVACAO OPERACAO_OBSERVACAO,
O.USUALTERACAO USUARIO_OPERACAO,
TO_CHAR(T.DTAQUITACAO, 'DD/MM/YYYY') DTA_QUITACAO
FROM (SELECT T.NROEMPRESA EMP, T.NROTITULO NUMERONF, T.SEQPESSOA, T.LINKERP, T.CODESPECIE, T.SEQTITULO,
MIN(T.DTAINCLUSAO) DTA_ENTRADA,
MAX(T.DTAQUITACAO) DTAQUITACAO,
SUM(T.VLRORIGINAL) VLR_TOTAL,
MAX(NVL(CT.PERCDESCCONTRATO, 0)) PERCDESCCONTRATO,
MAX(NVL(CT.VLRDESCCONTRATO, 0)) VLRDESCCONTRATO
FROM FI_TITULO T
LEFT JOIN FI_COMPLTITULO CT ON CT.SEQTITULO = T.SEQTITULO
WHERE T.CODESPECIE IN ('DUPP', 'CONTLG', 'ACRLOG')
AND T.SITUACAO != 'C'
AND T.NROEMPRESA IN (#LS1)
AND TRUNC(T.DTAINCLUSAO) BETWEEN :DT1 AND :DT2
GROUP BY T.NROEMPRESA, T.NROTITULO, T.SEQPESSOA, T.LINKERP, T.CODESPECIE, T.SEQTITULO) T
INNER JOIN GE_PESSOA G ON G.SEQPESSOA = T.SEQPESSOA
LEFT JOIN (SELECT X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA, X.LINKERP,
MAX(CASE WHEN CF.DESCRICAO LIKE 'FID%' THEN F.PERCENTUAL ELSE 0 END) PERC_FID,
SUM(CASE WHEN CF.DESCRICAO LIKE 'FID%' THEN F.PERCENTUAL * F.VLTTOTALITEM / 100 ELSE 0 END) VLR_FIDELIDADE,
MAX(CASE WHEN CF.DESCRICAO LIKE '%LOG%' THEN F.PERCENTUAL ELSE 0 END) PERC_LOG,
SUM(CASE WHEN CF.DESCRICAO LIKE '%LOG%' THEN F.PERCENTUAL * F.VLTTOTALITEM / 100 ELSE 0 END) VLR_LOGISTICO
FROM MLF_NOTAFISCAL X
INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF
INNER JOIN MLF_DESCFINACONTRATO F ON F.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
AND F.SEQITEMNF = XI.SEQITEMNF
AND F.LINKERP = X.LINKERP
AND F.PERCENTUAL > 0
INNER JOIN MGC_CONTRATODESCONTO CF ON CF.SEQCONTRATODESCONTO = F.SEQCONTRATODESCONTO
AND (CF.DESCRICAO LIKE 'FID%' OR CF.DESCRICAO LIKE '%LOG%')
GROUP BY X.NROEMPRESA, X.NUMERONF, X.SEQPESSOA, X.LINKERP) C ON C.NROEMPRESA = T.EMP
AND C.SEQPESSOA = T.SEQPESSOA
AND C.LINKERP = T.LINKERP
LEFT JOIN (SELECT O.SEQTITULO,
CASE WHEN O.CODOPERACAO = 19 THEN 'Compensação com Título a Receber' ELSE O.OBSERVACAO END FORMA_PAGAMENTO,
O.DTAOPERACAO DTA_OPERACAO,
O.VLROPERACAO,
O.OBSERVACAO,
O.USUALTERACAO
FROM FI_TITOPERACAO O
WHERE NVL(O.OPCANCELADA, 'N') != 'C'
AND O.CODOPERACAO != 16) O ON O.SEQTITULO = T.SEQTITULO
ORDER BY 5, 1;
