-- Solicitação via Teams, Flaviane. 14/04

SELECT
    F.SEQFORNECEDOR COD_FORNECEDOR,
    X.NOMERAZAO FORNECEDOR,
    X.NROCGCCPF || X.DIGCGCCPF AS CNPJ,
    'Prestador de Serviço' AS TIPFORNECEDOR,
    TO_CHAR(X.DTAINCLUSAO, 'DD/MM/YYYY') AS DTACADASTRO
FROM 
    GE_PESSOA X
JOIN 
    MAF_FORNECEDOR F
    ON F.SEQFORNECEDOR = X.SEQPESSOA
WHERE 
    F.TIPFORNECEDOR = 'S'
    AND X.DTAINCLUSAO BETWEEN :DT1 AND :DT2
ORDER BY 
    X.DTAINCLUSAO ASC
