-- Solicitação para atender a visualização das promoções replicadas do encarte.
-- Mago julaino me ajudou muito, tmj

SELECT DISTINCT X.SEQPROMOCPDV CODPROMOC, A.COMPRADOR, NVL(S.SEQPRODUTO,F.SEQPRODUTO) PLU, FIN.SEQFAMILIA FAMILIA, FIN.DESCCOMPLETA DESCRICAO_ITEM, X.DESCRICAO, 
       TO_CHAR(X.DTAINICIO, 'DD/MM/YYYY') INICIO, TO_CHAR(X.DTAFIM, 'DD/MM/YYYY') FIM, B.PRECOVALIDNORMAL PRECO_ATUAL, X.PRECOPROMOCAO * X.QTDAPARTIRDE PRECO_PROMOCIONAL,
       CASE 
         WHEN EXISTS 
           (SELECT 1 FROM consinco.MRL_ENCARTE AA INNER JOIN MRL_ENCARTEPRODUTO PP ON PP.SEQENCARTE = AA.SEQENCARTE AND PP.SEQPRODUTO = FIN.SEQPRODUTO AND X.DESCRICAO LIKE AA.SEQENCARTE||'%') 
           THEN 'Sim'  
             ELSE 'Não' END EXISTE_ITEM_ENCARTE,  
NULL OBSERVACAO
FROM CONSINCO.NAGV_BASE_PROMOC_PDV_MN_SF X INNER JOIN CONSINCO.MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO 
                                           INNER JOIN CONSINCO.MAP_PRODUTO F ON F.SEQFAMILIA = P.SEQFAMILIA
                                            LEFT JOIN CONSINCO.MAP_PRODSIMILAR C ON C.SEQPRODUTO = X.SEQPRODUTO 
                                            LEFT JOIN CONSINCO.MAP_PRODSIMILAR S ON S.SEQSIMILARIDADE = C.SEQSIMILARIDADE
                                           INNER JOIN MAP_PRODUTO FIN ON FIN.SEQPRODUTO = NVL(S.SEQPRODUTO,F.SEQPRODUTO) 
                                           INNER JOIN CONSINCO.MAP_FAMDIVISAO Z ON Z.SEQFAMILIA = F.SEQFAMILIA
                                           INNER JOIN CONSINCO.MAX_COMPRADOR A ON A.SEQCOMPRADOR = Z.SEQCOMPRADOR
                                            LEFT JOIN CONSINCO.MRL_PRODEMPSEG B ON B.SEQPRODUTO = NVL(S.SEQPRODUTO,F.SEQPRODUTO)  AND B.NROSEGMENTO = 2 
                                                                                                               AND B.NROEMPRESA = 46 
                                                                                                               AND B.QTDEMBALAGEM = 1
WHERE X.SEQPROMOCPDV = :NR1 AND NOT EXISTS (SELECT 1 FROM MAP_SIMILARIDADE SM WHERE SM.SEQSIMILARIDADE = S.SEQSIMILARIDADE AND SM.TIPOSIMILARIDADE != 'S')
