Ticket: 775254
--View que o time de price acabou descartando

SELECT NVL(XII.SEQPRODUTO, XIII.SEQPRODUTO)  PLU, XIV.DESCCOMPLETA DESCRICAO, XIII.VALOR_MEUNAGUMO VALOR_MEU_NAGUMO,
XII.VALOR_OFERTA VALOR_OFERTA_NORMAL,
CASE WHEN XIII.SEQPRODUTO IS NOT NULL THEN 'SIM' ELSE 'NAO' END EXISTE_MEU_NAGUMO,
  CASE WHEN XII.SEQPRODUTO  IS NOT NULL THEN 'SIM' ELSE 'NAO' END EXISTE_OFERTA,
    TO_CHAR(LEAST(NVL(XIII.DTAINICIO, XII.DTAINICIO), NVL(XII.DTAINICIO, XIII.DTAINICIO)), 'DD/MM/YYYY') || ' A ' ||
       TO_CHAR(GREATEST(NVL(XIII.DTAFIM, XII.DTAFIM), NVL(XII.DTAFIM, XIII.DTAFIM)), 'DD/MM/YYYY') PERIODO
FROM (SELECT Y.SEQPRODUTO, MIN(Y.PRECOPROMOCIONAL) VALOR_OFERTA, MIN(X.DTAINICIO)        DTAINICIO, MAX(X.DTAFIM)           DTAFIM
FROM CONSINCO.MRL_PROMOCAO X 
INNER JOIN CONSINCO.MRL_PROMOCAOITEM Y ON Y.SEQPROMOCAO = X.SEQPROMOCAO
AND Y.NROEMPRESA  = X.NROEMPRESA AND Y.CENTRALLOJA = X.CENTRALLOJA AND Y.NROSEGMENTO = X.NROSEGMENTO
WHERE X.SEQPROMOCAO = 266572
GROUP BY Y.SEQPRODUTO) XII
FULL OUTER JOIN (SELECT Z.SEQPRODUTO,
MIN(Z.PRECOPROMOCAO * Z.QTDAPARTIRDE) VALOR_MEUNAGUMO,
MIN(Z.DTAINICIO) DTAINICIO,
MAX(Z.DTAFIM) DTAFIM
FROM CONSINCO.NAGV_BASE_PROMOC_PDV_MN_SF Z
WHERE Z.SEQPROMOCPDV = 28161
GROUP BY Z.SEQPRODUTO) XIII
ON XIII.SEQPRODUTO = XII.SEQPRODUTO
INNER JOIN CONSINCO.MAP_PRODUTO XIV ON XIV.SEQPRODUTO = NVL(XII.SEQPRODUTO, XIII.SEQPRODUTO)
WHERE XIII.SEQPRODUTO IS NULL
ORDER BY XIV.DESCCOMPLETA
