SELECT
  U.NROSEGMENTO,
  U.DESCSEGMENTO,
  A.NROPEDCLIENTE,
  A.NROEMPRESA,
  NVL(B.NUMERODF, 0) AS NOTA,
  B.SERIEDF,
  B.NROSERIEECF,
  A.NROCARGA AS TITULO,
  A.NROPEDVENDA,
  A.NROPEDIDOAFV AS PEDIDO,
  Q.NOMEREDUZIDO,
  A.DTAINCLUSAO,
  A.SEQPESSOA,
  C.NOMERAZAO,
  SUM(
      ROUND(
          B.VLREMBINFORMADO * B.QTDPEDIDA / B.QTDEMBALAGEM,
          2
      )
  ) AS VALOR,
  CASE
    WHEN A.SITUACAOPED = 'W' THEN 'SEPARADO'
    WHEN A.SITUACAOPED = 'S' THEN 'SEPARACAO'
    WHEN A.SITUACAOPED = 'R' THEN 'ROTERIZACAO'
    WHEN A.SITUACAOPED = 'P' THEN 'PENDENTES'
    WHEN A.SITUACAOPED = 'L' THEN 'LIBERADO'
    WHEN A.SITUACAOPED = 'F' THEN 'FATURADO'
    WHEN A.SITUACAOPED = 'D' THEN 'DIGITACAO'
    WHEN A.SITUACAOPED = 'C' THEN 'CANCELADO'
    WHEN A.SITUACAOPED = 'A' THEN 'ANALISE'
    ELSE A.SITUACAOPED
  END AS STATUS_PEDIDO
FROM CONSINCO.MAD_PEDVENDA A
INNER JOIN CONSINCO.MAD_PEDVENDAITEM B
   ON A.NROPEDVENDA = B.NROPEDVENDA
  AND A.NROEMPRESA  = B.NROEMPRESA
INNER JOIN CONSINCO.GE_PESSOA C
   ON A.SEQPESSOA = C.SEQPESSOA
INNER JOIN CONSINCO.MAX_EMPRESA Q
   ON Q.NROEMPRESA = A.NROEMPRESA
INNER JOIN CONSINCO.MAD_SEGMENTO U
   ON A.NROSEGMENTO = U.NROSEGMENTO
WHERE 1 = 1
AND (
      :LT1 IS NULL
      OR TRIM(:LT1) IS NULL
      OR UPPER(TRIM(A.NROPEDCLIENTE)) LIKE '%' || UPPER(TRIM(:LT1)) || '%'
    )
GROUP BY
  A.NROEMPRESA,
  Q.NOMEREDUZIDO,
  A.NROPEDCLIENTE,
  U.NROSEGMENTO,
  U.DESCSEGMENTO,
  A.NROPEDVENDA,
  A.NROCARGA,
  A.DTAINCLUSAO,
  A.SEQPESSOA,
  C.NOMERAZAO,
  A.SITUACAOPED,
  A.NROPEDIDOAFV,
  B.NUMERODF,
  B.SERIEDF,
  B.NROSERIEECF;
