-- Ticket: 763272

SELECT A.SEQPESSOA, B.NOMERAZAO, A.NROEMPRESA LOJA, C.DESCRICAO ESPECIE, A.NROTITULO TITULO,
TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY') EMISSAO, TO_CHAR(A.DTAPROGRAMADA, 'DD/MM/YYYY') DATA_PROGRAMADA, TO_CHAR(A.DTAVENCIMENTO, 'DD/MM/YYYY') VENCIMENTO,
A.VLRNOMINAL VLRLIQ, (NVL(A.VLRNOMINAL, 0) - NVL(A.VLRPAGO, 0)) VLRABERTO, A.OBSERVACAO, A.USUALTERACAO USUARIO
FROM FI_TITULO A, GE_PESSOA B, FI_ESPECIE C
WHERE B.SEQPESSOA = A.SEQPESSOA
AND C.NROEMPRESAMAE = A.NROEMPRESAMAE
AND C.CODESPECIE = A.CODESPECIE
AND A.CODESPECIE = 'ANTPAG'
AND A.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
ORDER BY A.DTAINCLUSAO DESC;
