-- Solicitação Gabriel Falconi, via Teams

SELECT X.NRO_ACORDO, Y.SEQTITULO, Y.VLRORIGINAL VALOR, Y.VLRPAGO VALOR_PAGO,
Y.VLRORIGINAL - Y.VLRPAGO VALOR_ABERTO, TO_CHAR(Y.DTAEMISSAO, 'dd/mm/yyyy') DATA, X.FORNECEDOR, W.DESCRICAO REDE, Y.CODESPECIE ESPECIE
FROM CONSINCO.NAGV_TAE_ACORDOS_V4 X
INNER JOIN CONSINCO.FI_TITULO Y ON Y.NROTITULO = X.NRO_ACORDO
AND Y.SEQPESSOA = X.COD_FORNECEDOR
AND Y.NROEMPRESA = X.NRO_EMPRESA
INNER JOIN CONSINCO.GE_REDEPESSOA Z ON Z.SEQPESSOA = X.COD_FORNECEDOR
INNER JOIN CONSINCO.GE_REDE W ON W.SEQREDE = Z.SEQREDE
WHERE X.DATA_EMISSAO BETWEEN :DT1 AND :DT2
AND (Y.VLRORIGINAL - NVL(Y.VLRPAGO, 0)) > 0
#LTA
ORDER BY Y.DTAEMISSAO DESC, X.NRO_ACORDO, Y.SEQTITULO
