-- View ez solicitada pela Isabela (Falconi) Chamado/Teams

SELECT DISTINCT X.NROEMPRESA LOJA, X.SEQPRODUTO SKU, X.ESTQMINIMOLOJA ESTOQUE_MINIMO
FROM consinco.MRL_PRODUTOEMPRESA X
WHERE X.NROEMPRESA IN (#LS1)
AND X.NROEMPRESA <= 63
AND X.ESTQMINIMOLOJA >0
ORDER BY X.NROEMPRESA ASC;
