-- Solicitação Mônica
-- Ticket: 743131

SELECT X.NROEMPRESA EMPRESA, TO_CHAR(Y.DTAENTRADA, 'DD/MM/YYYY') DATA_ENTRADA, X.NROCARGARECEB CARGA, X.NUMERONF NUMERO_NF, Y.SEQPESSOA || ' - ' || Z.NOMERAZAO FORNECEDOR, SUM(A.VLRITEM)VALOR, 'FOB' FRETE
FROM CONSINCO.MAD_CARGARECEBNF X 
JOIN CONSINCO.MLF_NOTAFISCAL Y ON Y.SEQAUXNOTAFISCAL = X.SEQAUXNOTAFISCAL
JOIN CONSINCO.GE_PESSOA Z ON Z.SEQPESSOA = Y.SEQPESSOA
JOIN CONSINCO.MLF_NFITEM A ON A.SEQNF = Y.SEQNF
JOIN CONSINCO.TMP_M000_NF B ON B.M000_NR_CHAVE_ACESSO = Y.NFECHAVEACESSO
JOIN CONSINCO.TMP_M006_TRANSPORTE C ON C.M000_ID_NF = B.M000_ID_NF
WHERE C.M006_DM_FRETE = 1
AND X.NROEMPRESA IN (501, 502, 503, 504, 505, 506, 507, 508, 603)
AND TRUNC(Y.DTAENTRADA) BETWEEN :DT1 AND :DT2
GROUP BY X.NROEMPRESA, TO_CHAR(Y.DTAENTRADA, 'DD/MM/YYYY'), X.NROCARGARECEB, X.NUMERONF, Y.SEQPESSOA, Z.NOMERAZAO, Y.DTAENTRADA
ORDER BY Y.DTAENTRADA DESC, X.NROEMPRESA, X.NROCARGARECEB, X.NUMERONF;
