SELECT
    NF.NROEMPRESA AS LOJA,
    NF.NUMERONF AS NOTA,
    NF.SERIENF AS SERIE,
    TO_CHAR(NF.DTAEMISSAO, 'DD/MM/YYYY') AS DTA_EMISSAO,
    TO_CHAR(:DT2, 'DD/MM/YYYY') AS DTAMOVIMENTO,
    TO_CHAR(AUX.DTAVENCIMENTO, 'DD/MM/YYYY') AS DTA_VENCIMENTO,
    TO_CHAR(AUX.VLRORIGINAL, 'FM999G999G990D00') AS VALOR_TOTAL,
    P.NOMERAZAO AS FORNECEDOR,
    NF.USULANCTO AS USUARIO_LANCAMENTO,
    TO_CHAR(NF.DTAHORLANCTO, 'DD/MM/YYYY HH24:MI:SS') AS DTAHOR_LANCAMENTO,
    C.CODESPECIEFIN AS CODESPECIE
FROM CONSINCO.MLF_NOTAFISCAL NF
LEFT JOIN CONSINCO.GE_PESSOA P
    ON P.SEQPESSOA = NF.SEQPESSOA
LEFT JOIN CONSINCO.MRL_TITULOFIN AUX
    ON AUX.SEQAUXNOTAFISCAL = NF.SEQAUXNOTAFISCAL
INNER JOIN CONSINCO.MAX_CODGERALOPER C
    ON C.CODGERALOPER = NF.CODGERALOPER
   AND C.GERTITFINANCEIRO = 'S'
WHERE TRUNC(AUX.DTAVENCIMENTO) = TRUNC(:DT1)
  AND TRUNC(NF.DTAENTRADA) BETWEEN TRUNC(:DT2) AND TRUNC(:DT1)
  AND NF.TIPNOTAFISCAL = 'E'
  AND NF.SEQPESSOA > 999
  AND EXISTS (
        SELECT 1
          FROM CONSINCO.FI_ESPECIE E
         WHERE E.CODESPECIE = C.CODESPECIEFIN
           AND E.OBRIGDIREITO = 'O'
           AND E.CODESPECIE IN (
               'AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
               'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
               'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
               'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
               'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
               'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
               'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
               'SEGURO','SERVPJ','SUPERT','TEL','VLDESC'
           )
    )

UNION ALL

SELECT
    D.NROEMPRESA AS LOJA,
    D.NRONOTA AS NOTA,
    NULL AS SERIE,
    TO_CHAR(D.DTAEMISSAO, 'DD/MM/YYYY') AS DTA_EMISSAO,
    TO_CHAR(D.DTAENTRADA, 'DD/MM/YYYY') AS DTAMOVIMENTO,
    TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS DTA_VENCIMENTO,
    TO_CHAR(T.VLRORIGINAL, 'FM999G999G990D00') AS VALOR_TOTAL,
    P.NOMERAZAO AS FORNECEDOR,
    D.USUALTERACAO AS USUARIO_LANCAMENTO,
    TO_CHAR(D.DTAALTERACAO, 'DD/MM/YYYY HH24:MI:SS') AS DTAHOR_LANCAMENTO,
    T.CODESPECIE AS CODESPECIE
FROM CONSINCO.OR_NFDESPESA D
INNER JOIN CONSINCO.FI_TITULO T
    ON T.SEQPESSOA  = D.SEQPESSOA
   AND T.NROTITULO  = D.NRONOTA
   AND T.NROEMPRESA = D.NROEMPRESA
   AND T.LINKERP    = D.LINKERP
INNER JOIN CONSINCO.GE_PESSOA P
    ON P.SEQPESSOA = D.SEQPESSOA
WHERE D.SEQPESSOA > 999
  AND D.SITUACAO = 'I'
  AND TRUNC(D.DTAENTRADA) = TRUNC(:DT2)
  AND TRUNC(T.DTAVENCIMENTO) = TRUNC(:DT1)
  AND EXISTS (
        SELECT 1
        FROM CONSINCO.FI_ESPECIE E
        WHERE E.CODESPECIE = T.CODESPECIE
          AND E.OBRIGDIREITO = 'O'
          AND E.CODESPECIE IN (
              'AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
              'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
              'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
              'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
              'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
              'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
              'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
              'SEGURO','SERVPJ','SUPERT','TEL','VLDESC'
          )
    )
ORDER BY LOJA, DTAMOVIMENTO, NOTA;
