-- Query meh, solicitação via Teams - Liliane Orç 26/01.

SELECT 
x.NROCGCCPF CNPJ, 
x.DIGCGCCPF DIGITO, 
x.NOMERAZAO FORNECEDOR,
x.SEQPESSOA CODIGO, 
x.STATUS STATUS
  FROM consinco.GE_PESSOA x
  WHERE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) = :LT1
