SELECT
    a.NROEMPRESA       EMPRESA,
    a.NROREQUISICAO  REQUISICAO,
    a.SEQPESSOA          CODFORNEC,
    c.NOMERAZAO         FORNECEDOR,
    n.NRONOTA              NOTA,
    n.VALOR                    VALOR,
    TO_CHAR(n.DTAENTRADA,'DD-MM-YYYY') AS LANCAMENTO
FROM CONSINCO.OR_REQUISICAO a
INNER JOIN CONSINCO.GE_PESSOA c
    ON c.SEQPESSOA = a.SEQPESSOA
LEFT JOIN CONSINCO.OR_NFDESPESAREQ r
    ON r.SEQREQUISICAO = a.SEQREQUISICAO
LEFT JOIN CONSINCO.OR_NFDESPESA n
    ON n.SEQNOTA = r.SEQNOTA
   AND n.SEQPESSOA = a.SEQPESSOA   
WHERE a.NROEMPRESA IN (#LS1)
  AND a.SEQPESSOA = #NR1
  AND TRUNC(n.DTAENTRADA) BETWEEN :DT1 AND :DT2
ORDER BY a.NROEMPRESA, a.NROREQUISICAO;
