-- Solicitação Samara Alves via zap
-- Ticket: ?

SELECT DISTINCT X.SEQGERCOMPRA LOTE, X.SEQFORNECEDOR FORN, Z.NOMERAZAO FORNEC, X.NROEMPRESA NROLOJA, V.NOMEREDUZIDO LOJA, X.SEQPRODUTO CODIGO,
W.DESCCOMPLETA DESCRICAO, x.qtdembalagem EMBAL, X.QTDPEDIDA / X.QTDEMBALAGEM PEDIDO, ROUND(X.TFVLRCUSTOBASE * X.QTDEMBALAGEM, 2) CUSTO
FROM CONSINCO.MAC_GERCOMPRAITEM X
INNER JOIN CONSINCO.MAC_GERCOMPRA Y ON Y.SEQGERCOMPRA = X.SEQGERCOMPRA
INNER JOIN CONSINCO.GE_PESSOA Z ON Z.SEQPESSOA = X.SEQFORNECEDOR
INNER JOIN CONSINCO.MAP_PRODUTO W ON W.SEQPRODUTO = X.SEQPRODUTO
INNER JOIN CONSINCO.GE_EMPRESA V ON V.NROEMPRESA = X.NROEMPRESA
WHERE X.SEQGERCOMPRA = :NR1
AND X.QTDPEDIDA > 0
ORDER BY X.NROEMPRESA ASC, W.DESCCOMPLETA ASC
