-- Ticket: 690911

SELECT DISTINCT
       A.SEQTAREFA,
       P.PRODUTIVO,
       T.ATIVIDADE,
       PC.TIPOETQPALETECARREG || PC.SEQPALETECARREG AS ETIQUETA_MASTER,
       TO_CHAR(R.DTAHORINITAREFA, 'DD/MM/YYYY HH24:MI:SS') AS DT_INICIO,
       TO_CHAR(R.DTAHORFIMTAREFA, 'DD/MM/YYYY HH24:MI:SS') AS DT_FIM
  FROM MLO_ATIVIDADE A
  JOIN MLO_TIPATIVIDADE T
    ON T.CODTIPATIVIDADE = A.CODTIPATIVIDADE
   AND T.NROEMPRESA = A.NROEMPRESA
  JOIN MLO_TAREFAPRODUT TP
    ON TP.SEQTAREFA = A.SEQTAREFA
   AND TP.MESANO = A.MESANO
   AND TP.NROEMPRESA = A.NROEMPRESA
  JOIN MLO_PRODUTIVO P
    ON P.CODPRODUTIVO = TP.CODPRODUTIVO
   AND P.NROEMPRESA = TP.NROEMPRESA
  JOIN MLO_TAREFA R
    ON R.SEQTAREFA = TP.SEQTAREFA
   AND R.MESANO = TP.MESANO
   AND R.NROEMPRESA = TP.NROEMPRESA
  LEFT JOIN MLO_PALETECARREG PC
    ON PC.SEQPALETECARREG = A.SEQPALETECARREG
   AND PC.NROEMPRESA = A.NROEMPRESA
 WHERE A.NROEMPRESA IN ('507')
   AND TRUNC(R.DTAHORINITAREFA) BETWEEN :DT1 AND :DT2
   AND UPPER(T.ATIVIDADE) = 'MOVIMENTAÇÃO DE MASTER'
 ORDER BY P.PRODUTIVO, DT_INICIO
