-- Solicitação Flaviane para consultar o que o pessoal do CD ta mexendo (Select somente para log)
-- Ticket: 761829

SELECT P.SEQPRODUTO AS PLU, P.DESCCOMPLETA AS PRODUTO, 'Revenda' AS FINALIDADE, 'Composto para Separação' AS PROCESSO, NVL(A.USUAUDITORIA, 'SEM LOG') AS USUARIO_ALTERACAO,
A.DTAHORAUDITORIA AS DATA_HORA_ALTERACAO
FROM CONSINCO.MAP_PRODUTO P
INNER JOIN CONSINCO.MAP_FAMDIVISAO D ON D.SEQFAMILIA = P.SEQFAMILIA
LEFT JOIN (SELECT X.SEQIDENTIFICA, X.USUAUDITORIA, X.DTAHORAUDITORIA, ROW_NUMBER() OVER (PARTITION BY X.SEQIDENTIFICA
ORDER BY X.DTAHORAUDITORIA DESC, X.SEQAUDITORIA DESC) AS RN
FROM CONSINCO.MAP_AUDITORIA X
WHERE X.TABELA = 'MAP_PRODUTO'
AND X.CAMPO = 'INDPROCFABRICACAO'
AND X.VLRATUAL = 'C') A ON A.SEQIDENTIFICA = P.SEQPRODUTO AND A.RN = 1
WHERE D.FINALIDADEFAMILIA = 'R'
AND P.INDPROCFABRICACAO = 'C'
ORDER BY P.SEQPRODUTO;
