--Solicitação Daniela (RH)
--Para visualizar os impostos do SEQ 662721
--Ticket: 761403

SELECT LPAD(K.NROEMPRESA, 3, '0') || '-' || M.NOMEREDUZIDO AS LOJA, FT.NROTITULO TITULO, P.NOMERAZAO RAZAO_FORNECEDOR,
TO_CHAR(FT.DTAVENCIMENTO, 'DD/MM/YYYY') VENCTO, TO_CHAR(FT.DTAQUITACAO, 'DD/MM/YYYY') QUITACAO, NVL(K.VALOR, 0) VLR_DESPESA,
NVL(IMP.IMPOSTO, 0) IMPOSTO
FROM CONSINCO.OR_NFDESPESA K
INNER JOIN CONSINCO.FI_TITULO FT ON FT.NROEMPRESA = K.NROEMPRESA
AND FT.NROTITULO  = K.NRONOTA
AND FT.SEQPESSOA  = K.SEQPESSOA
INNER JOIN CONSINCO.GE_PESSOA P ON P.SEQPESSOA = K.SEQPESSOA
INNER JOIN CONSINCO.MAX_EMPRESA M ON M.NROEMPRESA = K.NROEMPRESA
LEFT JOIN (SELECT I.NROEMPRESA, I.NROTITULO, SUM(NVL(I.VLRORIGINAL, 0)) AS IMPOSTO
FROM CONSINCO.FI_TITULO I
WHERE I.SITUACAO != 'C'
AND I.CODESPECIE != 'DESP'
GROUP BY I.NROEMPRESA, I.NROTITULO) IMP ON IMP.NROEMPRESA = K.NROEMPRESA
AND IMP.NROTITULO = K.NRONOTA
WHERE K.SITUACAO = 'I'
AND FT.SITUACAO != 'C'
AND P.SEQPESSOA = 662721
AND FT.DTAVENCIMENTO BETWEEN :DT1 AND :DT2
ORDER BY FT.DTAVENCIMENTO, K.NROEMPRESA, FT.NROTITULO;
