SELECT X.NROEMPRESA EMPRESA, TO_CHAR(X.DTAHOREMISSAO, 'DD/MM/YYYY') DATA_EMISSAO, X.CODGERALOPER CGO, X.NUMERODF NOTA, X.SERIEDF SERIE,
X.SEQPESSOA || ' - ' || P.NOMERAZAO FORNECEDOR, Y.SEQPRODUTO PLU, SUM(Y.VLRITEM) VALOR_ITEM
FROM CONSINCO.MFL_DOCTOFISCAL X
JOIN CONSINCO.MFL_DFITEM Y ON Y.SEQNF = X.SEQNF
JOIN CONSINCO.GE_PESSOA P ON P.SEQPESSOA = X.SEQPESSOA
WHERE X.NROEMPRESA = 505
AND Y.SEQPRODUTO = 225663
AND TRUNC(X.DTAHOREMISSAO) BETWEEN :DT1 AND :DT2
GROUP BY X.NROEMPRESA,
 X.DTAHOREMISSAO, X.CODGERALOPER, X.NUMERODF, X.SERIEDF, X.SEQPESSOA,
P.NOMERAZAO, Y.SEQPRODUTO
ORDER BY X.DTAHOREMISSAO DESC, X.NUMERODF;
