-- Solicitação via Ticket da Falconi para extração de dados dos encartes.
-- Ticket: 726921

SELECT E.DESCRICAO CAMPANHA,
E.SEQENCARTE||' - '||E.DESCRICAO INFO_ENCARTE,
(
SELECT LISTAGG(EE.NROEMPRESA, ', ')
WITHIN GROUP (ORDER BY EE.NROEMPRESA)
FROM CONSINCO.MRL_ENCARTEEMP EE
WHERE EE.SEQENCARTE = E.SEQENCARTE
) LOJAS,
TO_CHAR(NVL(E.DTAVIGENCIAINI, E.DTAINICIO), 'DD/MM/YYYY') DTA_INICIO,
TO_CHAR(NVL(E.DTAVIGENCIAFIM, E.DTAFIM),  'DD/MM/YYYY')   DTA_FIM,
E.PAGINA PAG,
E.NOMEPAGINA DESC_PAG,
E.COMPRADOR,
E.SEQPRODUTO  PLU,
E.DESCRICAOPRODUTO   DESCRICAO,
E.PRECOATUAL   PRECOATUAL,
NAG.PRECOPROMOCIONAL PRECO_PROMOC_NAGUMO_SP,
RIO.PRECOPROMOCIONAL PRECO_PROMOC_RIO,
MIX.PRECOPROMOCIONAL PRECO_PROMOC_MIXTER
FROM CONSINCO.NAGV_ENCARTE E
LEFT JOIN CONSINCO.NAGV_ENCARTE NAG
         ON NAG.SEQENCARTE = E.SEQENCARTE
        AND NAG.SEQPRODUTO = E.SEQPRODUTO
        AND NAG.SEQORDEM   = E.SEQORDEM
        AND NAG.NROAGRUPAMENTO  = 2
LEFT JOIN CONSINCO.NAGV_ENCARTE RIO
         ON RIO.SEQENCARTE = E.SEQENCARTE
        AND RIO.SEQPRODUTO = E.SEQPRODUTO
        AND RIO.SEQORDEM   = E.SEQORDEM
        AND RIO.NROAGRUPAMENTO  = 3
LEFT JOIN CONSINCO.NAGV_ENCARTE MIX
         ON MIX.SEQENCARTE = E.SEQENCARTE
        AND MIX.SEQPRODUTO = E.SEQPRODUTO
        AND MIX.SEQORDEM   = E.SEQORDEM
        AND MIX.NROAGRUPAMENTO  = 4
WHERE E.NROAGRUPAMENTO = 2
AND E.DTAINICIO BETWEEN :DT1 AND :DT2
AND EXISTS (
       SELECT 1
       FROM CONSINCO.MRL_ENCARTEPRODUTO A
       WHERE A.SEQENCARTE = E.SEQENCARTE
       AND A.SEQPRODUTO = E.SEQPRODUTO
       AND A.NROPAGINA  = E.PAGINA
       AND A.SEQORDEM   = E.SEQORDEM
   )
 ORDER BY E.DTAINICIO,
          E.SEQENCARTE,
          E.PAGINA,
          E.SEQORDEM;
