SELECT DISTINCT
       PC.NROEMPRESA EMPRESA,
       'V' || RF.SEQPALETERF || RF.SEQPALETEQTDE ETIQUETA_LOTE,
       TO_CHAR(PC.DTAHORINIMONT, 'DD/MM/YYYY') DATA_MONTAGEM,
       PC.USUMONTAGEM USUARIO,
       CASE
         WHEN PC.STATUSCARREG = 'C' THEN 'Carregada'
         WHEN PC.STATUSCARREG = 'E' THEN 'Em Montagem'
         WHEN PC.STATUSCARREG = 'M' THEN 'Montada'
         WHEN PC.STATUSCARREG = 'N' THEN 'Cancelada'
         WHEN PC.STATUSCARREG = 'R' THEN 'Em Carregamento'
         WHEN PC.STATUSCARREG = 'T' THEN 'Transferência Entre Áreas'
         WHEN PC.STATUSCARREG = 'A' THEN 'Em Agrupamento'
         WHEN PC.STATUSCARREG = 'B' THEN 'Agrupada'
         WHEN PC.STATUSCARREG = 'D' THEN 'Em Expedição'
         WHEN PC.STATUSCARREG = 'I' THEN 'Expedição'
         WHEN PC.STATUSCARREG = 'U' THEN 'Em Auditoria'
         ELSE NULL
       END STATUS,
       TO_CHAR(:frmQVConsultaExecuta.DT1, 'DD/MM/YYYY') DTA_INICIO,
       TO_CHAR(:frmQVConsultaExecuta.DT2, 'DD/MM/YYYY') DTA_FIM
  FROM MLO_PALETECARREG PC
  JOIN MLO_PALCARREGRF RF
    ON RF.SEQPALETECARREG = PC.SEQPALETECARREG
 WHERE PC.NROEMPRESA IN (502, 507, 508)
   AND TRUNC(PC.DTAHORINIMONT) BETWEEN :DT1
                                   AND :DT2
 ORDER BY STATUS, EMPRESA, ETIQUETA_LOTE
