SELECT
    P.SEQPRODUTO,
    P.DESCCOMPLETA AS PRODUTO,
    P.SEQFAMILIA,
    F.FAMILIA AS DESCRICAO_FAMILIA,
    'SIM' AS COMPRA_ATIVA,
    'SIM' AS VENDA_ATIVA,
    NVL(MPE.ESTQLOJA, 0) AS ESTQLOJA
FROM consinco.MAP_PRODUTO P
INNER JOIN consinco.MAP_FAMILIA F
        ON F.SEQFAMILIA = P.SEQFAMILIA
INNER JOIN consinco.MRL_PRODUTOEMPRESA MPE
        ON MPE.SEQPRODUTO = P.SEQPRODUTO
       AND MPE.NROEMPRESA = :NR1
WHERE P.SEQFAMILIA IN (
        SELECT DISTINCT P1.SEQFAMILIA
        FROM consinco.MAP_PRODUTO P1
        WHERE UPPER(P1.DESCCOMPLETA) LIKE '%' || UPPER(:LT1) || '%'
          AND SUBSTR(fStatusCompraProdutoEmpAtiva(P1.SEQPRODUTO, NULL), 1, 1) = 'A'
          AND SUBSTR(fStatusVendaProduto(P1.SEQPRODUTO, NULL, NULL), 1, 1) = 'A'
)
  AND SUBSTR(fStatusCompraProdutoEmpAtiva(P.SEQPRODUTO, NULL), 1, 1) = 'A'
  AND SUBSTR(fStatusVendaProduto(P.SEQPRODUTO, NULL, NULL), 1, 1) = 'A'
ORDER BY
    P.DESCCOMPLETA;
