-- Solicitação aleatória P. Cerconi dia 30/04/2026

SELECT
    C.NROCONTRATO CONTRATO,
    C.SEQCONTRATO,
    F.SEQPESSOA COD_FORNECEDOR,
    F.NOMERAZAO FORNECEDOR,

    C.INDSUBICMSVLRNET       AS ICMS,
    C.INDSUBICMSSTVLRNET     AS ICMS_ST,
    C.INDSUBIPIVLRNET        AS IPI,
    C.INDSUBPISVLRNET        AS PIS,
    C.INDSUBCOFINSVLRNET     AS COFINS,
    C.INDSUBICMSFCPVLRNET    AS ICMS_FCP,
    C.INDSUBICMSSTFCPVLRNET  AS ICMS_ST_FCP,

    C.INDSUBCBSVLRNET        AS CBS,
    C.INDSUBISVLRNET         AS IS_IMPOSTO,
    C.INDSUBIBSUFVLRNET      AS IBS_UF,
    C.INDSUBIBSMUNVLRNET     AS IBS_MUN

FROM CONSINCO.MGC_CONTRATO C
JOIN CONSINCO.GE_REDEPESSOA R
    ON R.SEQREDE = C.SEQREDE
   AND R.STATUS = 'A'
JOIN CONSINCO.GE_PESSOA F
    ON F.SEQPESSOA = R.SEQPESSOA

WHERE
       NVL(C.INDSUBICMSVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBICMSSTVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBIPIVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBPISVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBCOFINSVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBICMSFCPVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBICMSSTFCPVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBCBSVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBISVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBIBSUFVLRNET, 'N') = 'S'
    OR NVL(C.INDSUBIBSMUNVLRNET, 'N') = 'S'

ORDER BY F.NOMERAZAO;
