-- Ticket: 778948

SELECT DISTINCT X.NROCARGA CARGA, X.SEQPRODUTO PLU, Y.DESCCOMPLETA DESCRICAO_PRODUTO,
Z.QTDEMBALAGEM || ' - ' || Z.EMBALAGEM PADRAO_EMBALAGEM, XI.DESCRICAO TIPO_ARMAZENAGEM, XII.DESCLINHASEPAR LINHA_DE_SEPARACAO,
CASE XIIII.STATUSCARGA
  WHEN 'A' THEN 'Não Separada'
    WHEN 'C' THEN 'Gerando Carregamento'
      WHEN 'F' THEN 'Faturada'
        WHEN 'G' THEN 'Gerada'
          WHEN 'L' THEN 'Liberada'
            WHEN 'S' THEN 'Em Separação'
              WHEN 'T' THEN 'Termo de Liberação'
                WHEN 'X' THEN 'Iniciado Processo de Cancelamento'
                  END STATUS
FROM CONSINCO.MLO_CARGAEXPPROD X
INNER JOIN CONSINCO.MLO_CARGAEXPED XIIII ON XIIII.NROCARGA = X.NROCARGA
AND XIIII.NROEMPRESA = X.NROEMPRESA
INNER JOIN CONSINCO.MLO_PRODUTO Y ON Y.SEQPRODUTO = X.SEQPRODUTO
AND Y.NROEMPRESA = X.NROEMPRESA 
INNER JOIN CONSINCO.MLO_PRODEMBALAGEM Z ON Z.SEQPRODUTO = X.SEQPRODUTO
AND Z.NROEMPRESA = X.NROEMPRESA
AND Z.QTDEMBALAGEM = X.QTDEMBALAGEM
LEFT JOIN CONSINCO.MLO_PRODEMBWM XI ON XI.SEQPRODUTO = X.SEQPRODUTO
AND XI.QTDEMBALAGEM = X.QTDEMBALAGEM
AND XI.CODDEPOSITANTE = X.CODDEPOSITANTE
AND XI.NROEMPRESA = X.NROEMPRESA
AND EXISTS (SELECT 1 FROM CONSINCO.MLO_DISTRIBUICAOLINHA X
WHERE X.CODDISTRIBLINHA = XI.CODDISTRIBLINHA
AND X.NROEMPRESA = XI.NROEMPRESA
AND X.DESCDISTRIBLINHA = 'COLETOR')
LEFT JOIN CONSINCO.MLO_LINHASEPARACAO XII ON XII.CODLINHASEPAR = XI.CODLINHASEPAR
AND XII.CODDISTRIBLINHA = XI.CODDISTRIBLINHA
AND XII.NROEMPRESA = XI.NROEMPRESA
LEFT JOIN CONSINCO.MLOV_VDL_LISTATIPOARMAZENAGEM X ON X.CODIGO = Y.TIPARMAZENAGEM
WHERE X.NROCARGA = :NR1
AND X.NROEMPRESA = :LS1
