SELECT 
    p.SEQPESSOA,
    p.NOMERAZAO,
    p.FANTASIA,
    '(' || p.FONEDDD1 || ') ' || p.FONENRO1 AS TELEFONE,
    m.EMAILCONTATO,
    m.TIPFORNECEDOR,
    m.STATUSGERAL
FROM consinco.GE_PESSOA p
JOIN consinco.MAF_FORNECEDOR m 
    ON m.SEQFORNECEDOR = p.SEQPESSOA
ORDER BY p.NOMERAZAO;
