-- Ticket: 778072
-- Solicitado por: Lelelelele

SELECT 'SALDO' TIPO_REGISTRO, X.NROEMPRESA EMPRESA, X.SEQPRODUTO CODIGO_PRODUTO, XI.DESCCOMPLETA PRODUTO,
XVI.EMBALAGEM EMBALAGEM_COMPRA, X.ESTOQUE QUANTIDADE_ESTOQUE, X.ESTOQUE * XVII.CMULTVLRNF VALOR_CUSTO_BRUTO, Z.LOCAL LOCAL_OCORRENCIA,
NULL CGO, NULL DESCRICAO_CGO, NULL ENTRADA_SAIDA, NULL QUANTIDADE_MOVIMENTADA, NULL USUARIO_MOVIMENTACAO, NULL DATA_MOVIMENTACAO,
NULL NUMERO_NF, NULL SERIE_NF, NULL OBSERVACAO_NF, NULL HISTORICO 
FROM CONSINCO.MRL_PRODLOCAL X
INNER JOIN CONSINCO.MRL_LOCAL Z ON Z.SEQLOCAL = X.SEQLOCAL
AND Z.NROEMPRESA = X.NROEMPRESA
INNER JOIN CONSINCO.MAP_PRODUTO XI ON XI.SEQPRODUTO = X.SEQPRODUTO
INNER JOIN CONSINCO.MAX_EMPRESA XIV ON XIV.NROEMPRESA = X.NROEMPRESA
INNER JOIN CONSINCO.MAP_FAMDIVISAO XV ON XV.SEQFAMILIA = XI.SEQFAMILIA
AND XV.NRODIVISAO = XIV.NRODIVISAO
LEFT JOIN CONSINCO.MLO_PRODEMBALAGEM XVI ON XVI.SEQPRODUTO = X.SEQPRODUTO
AND XVI.NROEMPRESA = X.NROEMPRESA
AND XVI.QTDEMBALAGEM = XV.PADRAOEMBCOMPRA
AND XVI.STATUSEMBALAGEM = 'A'
LEFT JOIN CONSINCO.MRL_PRODUTOEMPRESA XVII ON XVII.SEQPRODUTO = X.SEQPRODUTO
AND XVII.NROEMPRESA = X.NROEMPRESA
WHERE X.NROEMPRESA = :LS1
AND Z.LOCAL IN ('OCORRENCIAS','REVERSA')
AND X.ESTOQUE <> 0

UNION ALL

SELECT 'MOVIMENTO' TIPO_REGISTRO, X.NROEMPRESA EMPRESA, X.SEQPRODUTO CODIGO_PRODUTO, Y.DESCCOMPLETA PRODUTO,
NULL EMBALAGEM_COMPRA, NULL QUANTIDADE_ESTOQUE, NULL VALOR_CUSTO_BRUTO, Z.LOCAL LOCAL_OCORRENCIA, X.CODGERALOPER CGO,
XI.DESCRICAO DESCRICAO_CGO, X.TIPLANCTO ENTRADA_SAIDA, X.QTDLANCTO QUANTIDADE_MOVIMENTADA, X.USULANCTO USUARIO_MOVIMENTACAO,
TO_CHAR(X.DTAENTRADASAIDA,'DD/MM/YYYY') DATA_MOVIMENTACAO, XII.NUMERONF NUMERO_NF, XII.SERIENF SERIE_NF, XII.OBSERVACAONFE OBSERVACAO_NF, X.HISTORICO HISTORICO
FROM CONSINCO.MRL_LANCTOESTOQUE X
INNER JOIN CONSINCO.MAP_PRODUTO Y ON Y.SEQPRODUTO = X.SEQPRODUTO
INNER JOIN CONSINCO.MRL_LOCAL Z
ON Z.SEQLOCAL = X.LOCAL
AND Z.NROEMPRESA = X.NROEMPRESA
INNER JOIN CONSINCO.MAX_CODGERALOPER XI
ON XI.CODGERALOPER = X.CODGERALOPER
LEFT JOIN CONSINCO.MLF_NOTAFISCAL XII
ON XII.SEQNF = X.SEQNF
WHERE X.NROEMPRESA = :LS1
AND X.DTAENTRADASAIDA >= :DT1
AND X.DTAENTRADASAIDA < :DT2 + 1
AND Z.LOCAL IN ('OCORRENCIAS','REVERSA')
