SELECT A.NROETQLOTESEPAR,
       B.NROEMPRESA,
       B.NROCARGA,
       B.CODDEPOSSEPAR,
       B.SEQLOTE,
       B.NROQUEBRA,
       D.NROBOX,
       C.DESCLINHASEPAR,
       B.NROPALETE,
       TO_CHAR(D.DTAHORGERACAO, 'DD/MM/YYYY HH24:MI:SS') AS DTA,
       D.DESTINO,
       '' AS TARJA,
       B.PESOTOTALLOTE   AS PESO,
       B.MCUBTOTALLOTE   AS METRAGEM_CUBICA,
       B.QTDITEM         AS ITENS,
       B.QTDVOLUME       AS VOLUMES,
       (SELECT MIN(Z.SEQPESSOA)
        FROM   consinco.MLO_CARGAECLIENTE Z
        WHERE  Z.NROCARGA = D.NROCARGA) AS LOJA,                
       (SELECT MIN(CCC.CODPRODUTIVO)
        FROM   consinco.MLO_ATIVIDADE    AAA,
               consinco.MLO_TAREFAPRODUT BBB,
               consinco.MLO_PRODUTIVO    CCC
        WHERE  AAA.MESANO           = BBB.MESANO
        AND    AAA.SEQTAREFA        = BBB.SEQTAREFA
        AND    AAA.NROEMPRESA       = BBB.NROEMPRESA
        AND    BBB.CODPRODUTIVO     = CCC.CODPRODUTIVO
        AND    BBB.NROEMPRESA       = CCC.NROEMPRESA
        AND    AAA.INDEXCLUSAO      = 'N'
        AND    AAA.STATUSATIVIDADE != 'X'
        AND    AAA.CODTIPATIVIDADE  = 'SE'
        AND    AAA.NROCARGA         = B.NROCARGA
        AND    AAA.CODDEPOSSEPAR    = B.CODDEPOSSEPAR
        AND    AAA.SEQLOTE          = B.SEQLOTE
        AND    AAA.NROQUEBRA        = B.NROQUEBRA
        AND    AAA.NROEMPRESA       = B.NROEMPRESA) AS PRODUTIVO, 
       LPAD(ROW_NUMBER() OVER (PARTITION BY B.NROCARGA, B.CODDEPOSSEPAR, B.NROEMPRESA
                               ORDER BY B.NROCARGA, B.CODDEPOSSEPAR, B.NROEMPRESA, B.SEQLOTE), 2, 0)
       || '/' ||
       LPAD((SELECT MAX(P.SEQLOTE)
               FROM CONSINCO.MLO_CARGAEPALETE P
              WHERE P.NROCARGA      = B.NROCARGA
                AND P.NROEMPRESA    = B.NROEMPRESA
                AND P.CODDEPOSSEPAR = B.CODDEPOSSEPAR), 2, 0) AS CONTROLELOTE
FROM   consinco.MLO_ETQLOTESEPAR   A,
       consinco.MLO_CARGAEPALETE   B,
       consinco.MLO_LINHASEPARACAO C,
       consinco.MLO_CARGAEXPED     D
WHERE  A.NROETQLOTESEPAR = B.NROETQLOTESEPAR
AND    C.CODLINHASEPAR   = B.TIPLOTE
AND    C.NROEMPRESA      = B.NROEMPRESA
AND    B.NROCARGA        = D.NROCARGA
AND    D.CODDEPOSSEPAR   = B.CODDEPOSSEPAR;
