-- Solicitado por: Mônica
-- Ticket: 743145
 
SELECT X.NROEMPRESA EMPRESA, TO_CHAR(X.DTAENTRADA, 'DD/MM/YYYY') DATA_ENTRADA, Y.NUMERODF NF_EMITIDA, Y.SERIEDF SERIE_NF_EMITIDA, X.NUMERONF NF_ENTRADA_MATA_OPERACAO, X.SERIENF SERIE_NF_ENTRADA
FROM CONSINCO.MLF_NOTAFISCAL X
JOIN CONSINCO.MFL_DOCTOFISCAL Y ON Y.SEQNF = X.SEQNFREF
WHERE X.NROEMPRESA IN (501, 502, 503, 504, 505, 506, 507, 508, 603)
AND TRUNC(X.DTAENTRADA) BETWEEN :DT1 AND :DT2
ORDER BY X.DTAENTRADA DESC, X.NROEMPRESA, Y.NUMERODF, X.NUMERONF
; ;
; ;
