Ticket: 776785
Solicitado por: Miriam

SELECT X.SEQPRODUTO PLU, X.DESCCOMPLETA DESCRICAO,
REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,1) CATEGORIA_NVL_1,
REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,2) CATEGORIA_NVL_2,
REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,3) CATEGORIA_NVL_3,
REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,4) CATEGORIA_NVL_4,
REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,5) CATEGORIA_NVL_5
FROM MAP_PRODUTO X
INNER JOIN CONSINCO.MRL_PRODUTOEMPRESA Y ON Y.SEQPRODUTO = X.SEQPRODUTO
INNER JOIN consinco.MRL_PRODEMPSEG XI ON XI.SEQPRODUTO = X.SEQPRODUTO
AND XI.NROEMPRESA = Y.NROEMPRESA 
LEFT JOIN (SELECT Y.SEQCATEGORIA, Z.CAMINHOCOMPLETO, Y.SEQFAMILIA
FROM MAP_FAMDIVCATEG Y
INNER JOIN MAP_CATEGORIA Z ON Z.SEQCATEGORIA = Y.SEQCATEGORIA
WHERE Y.STATUS = 'A'
AND Z.ACTFAMILIA = 'S' 
AND Z.TIPCATEGORIA = 'M') Z
ON Z.SEQFAMILIA = X.SEQFAMILIA
WHERE Y.STATUSCOMPRA = 'A'
AND XI.STATUSVENDA = 'A'
AND REGEXP_LIKE(CONVERT(UPPER(X.DESCCOMPLETA), 'US7ASCII'), NVL(REGEXP_REPLACE(CONVERT(UPPER(:LT1), 'US7ASCII'), '\s*,\s*', '|'), '.'))
AND NOT REGEXP_LIKE(NVL(CONVERT(UPPER(TRIM(REGEXP_SUBSTR(Z.CAMINHOCOMPLETO,'[^\]+',1,1))), 'US7ASCII'), 'X'), '^(ACOUGUE|ROTISSERI|PADARIA|PEIXARIA)')
GROUP BY X.SEQPRODUTO,
X.DESCCOMPLETA,
Z.CAMINHOCOMPLETO
HAVING SUM(NVL(Y.ESTQLOJA,0)) + SUM(NVL(Y.ESTQDEPOSITO,0)) + SUM(NVL(Y.ESTQTROCA,0)) > 0
ORDER BY X.SEQPRODUTO;
