Ticket: 724515
Solicitado por: Isabela

SELECT X.NROPEDIDOSUPRIM  AS NRO_PEDIDO,
X.NROEMPRESA   AS CD_ORIGEM,
Y.NROEMPDESTINO   AS LOJA_DESTINO,
COUNT(DISTINCT Y.SEQPRODUTO)  AS QTD_SKUS,
SUM(Y.QTDSOLICITADA) AS QTDE_SOLICITADA,
SUM(NVL(E.QTDEXPEDIDA,0)) AS QTDE_EXPEDIDA,
SUM(NVL(Y.QTDTOTTRANSITO,0)) AS QTDE_TRANSITO,
SUM(NVL(E.QTDCANCELADA,0))  AS QTDE_CANCELADA,
SUM(Y.QTDSOLICITADA
- NVL(E.QTDEXPEDIDA,0)
- NVL(E.QTDCANCELADA,0)
       ) AS QTDE_PENDENTE,
TO_CHAR(X.DTAEMISSAO,'DD/MM/YYYY') AS DTA_EMISSAO,
TO_CHAR(NVL(X.DTARECEBTO, X.DTALIMITERECEBTO),
'DD/MM/YYYY') AS DATA_RECEBIMENTO,
MAX(TRUNC(SYSDATE) - TRUNC(X.DTAEMISSAO))  AS DIAS_EM_CARTEIRA
FROM CONSINCO.MSU_PSITEMEXPEDIR Y
INNER JOIN CONSINCO.MSU_PEDIDOSUPRIM X
ON X.NROPEDIDOSUPRIM = Y.NROPEDIDOSUPRIM
AND X.NROEMPRESA     = Y.NROEMPRESA
AND X.CENTRALLOJA    = Y.CENTRALLOJA
INNER JOIN CONSINCO.MRL_PRODEMPSEG PS
ON PS.SEQPRODUTO = Y.SEQPRODUTO
AND PS.NROEMPRESA = Y.NROEMPDESTINO
AND PS.STATUSVENDA = 'A'
LEFT JOIN (
SELECT E.NROPEDIDOSUPRIM,
E.NROEMPRESA,
E.NROEMPDESTINO,
E.SEQPRODUTO,
SUM(NVL(E.QTDEXPEDIDA,0))  QTDEXPEDIDA,
SUM(NVL(E.QTDCANCELADA,0)) QTDCANCELADA
FROM CONSINCO.MSU_PSITEMEXPEDIDO E
GROUP BY E.NROPEDIDOSUPRIM,
E.NROEMPRESA,
E.NROEMPDESTINO,
 E.SEQPRODUTO
) E
ON E.NROPEDIDOSUPRIM = Y.NROPEDIDOSUPRIM
AND E.NROEMPRESA      = Y.NROEMPRESA
AND E.NROEMPDESTINO   = Y.NROEMPDESTINO
AND E.SEQPRODUTO      = Y.SEQPRODUTO
WHERE X.SITUACAOPED IN ('A','P')
AND (
Y.QTDSOLICITADA
- NVL(E.QTDEXPEDIDA,0)
- NVL(E.QTDCANCELADA,0)
    ) > 0
AND X.NROEMPRESA IN (#LS1)
AND X.DTAEMISSAO BETWEEN :DT1 AND :DT2
GROUP BY X.NROPEDIDOSUPRIM,
X.NROEMPRESA,
Y.NROEMPDESTINO,
X.DTAEMISSAO,
NVL(X.DTARECEBTO, X.DTALIMITERECEBTO)
ORDER BY X.DTAEMISSAO DESC,
X.NROPEDIDOSUPRIM;
