SELECT X.NROEMPRESA, Y.DESCCOMPLETA PRODUTO, X.SEQPRODUTO CODINTERNO,
TO_CHAR(X.DTAINICIO, 'DD/MM/YYYY') DATA_INICIO_OFERTA,
TO_CHAR(X.DTAFIM, 'DD/MM/YYYY') DATA_FIM_OFERTA,
X.PRECOPROMOCAO VALOR_PROMOCAO
FROM consinco.NAGV_BASE_PROMOC_PDV_MN X
INNER JOIN consinco.MAP_PRODUTO Y ON Y.SEQPRODUTO = X.SEQPRODUTO
WHERE X.STATUS = 'A'
AND SYSDATE BETWEEN X.DTAINICIO AND X.DTAFIM AND X.NROEMPRESA IN (:LS1)
ORDER BY X.NROEMPRESA, Y.DESCCOMPLETA;
