-- Ticket: 756190

SELECT DISTINCT A.NROEMPRESA AS EMPRESA, A.TIPOETQPALETECARREG || A.SEQPALETECARREG AS ETIQUETA_MASTER, G.FANTASIA AS AREA_ARMAZENAGEM,
TO_CHAR(A.DTAHORINIMONT, 'DD/MM/YYYY HH24:MI') AS INICIO_MONTAGEM, TO_CHAR(A.DTAHORFINALMONT, 'DD/MM/YYYY HH24:MI') AS FIM_MONTAGEM, A.USUMONTAGEM AS USUARIO,
CASE
  WHEN A.STATUSCARREG = 'C' THEN 'Carregada'
    WHEN A.STATUSCARREG = 'E' THEN 'Em Montagem'
      WHEN A.STATUSCARREG = 'M' THEN 'Montada'
        WHEN A.STATUSCARREG = 'N' THEN 'Cancelada'
          WHEN A.STATUSCARREG = 'R' THEN 'Em Carregamento'
            WHEN A.STATUSCARREG = 'T' THEN 'Transferência Entre Áreas'
              WHEN A.STATUSCARREG = 'A' THEN 'Em Agrupamento'
                WHEN A.STATUSCARREG = 'B' THEN 'Agrupada'
                  WHEN A.STATUSCARREG = 'D' THEN 'Em Expedição'
                    WHEN A.STATUSCARREG = 'I' THEN 'Expedição'
                      WHEN A.STATUSCARREG = 'U' THEN 'Em Auditoria'
ELSE NULL END AS STATUS,
  CASE
    WHEN NVL(P.TIPOCARGA, 'R') = 'R' THEN 'Recebimento'
      WHEN P.TIPOCARGA = 'E' THEN 'Expedição'
        ELSE NULL
          END AS TIPO_CARGA, MP.DESCCOMPLETA AS PRODUTO, PE.EMBALAGEM || ' - ' || Q.QTDEMBALAGEM AS EMBALAGEM, Q.QTDPALETE / Q.QTDEMBALAGEM AS QUANTIDADE,
TO_CHAR(Q.DTAVALIDADE, 'DD/MM/YYYY') AS DATA_VALIDADE, TO_CHAR(Q.DTARECEBIMENTO, 'DD/MM/YYYY') AS DATA_RECEBIMENTO, P.SEQPALETERF AS ORDEM_PALETE,
Q.SEQPALETEQTDE AS ORDEM_VOLUME
FROM CONSINCO.MLO_PALETECARREG A, CONSINCO.MLO_PALCARREGRF R,
CONSINCO.MLO_PALETE P, CONSINCO.MLO_PALETEQTDE Q,
CONSINCO.MLO_TIPESPECIE T, CONSINCO.GE_PESSOA G,
CONSINCO.MLO_PRODUTO MP, CONSINCO.MLO_PRODEMBALAGEM PE
WHERE R.SEQPALETECARREG = A.SEQPALETECARREG
AND P.SEQPALETERF = Q.SEQPALETERF AND P.SEQPALETERF = R.SEQPALETERF
AND Q.SEQPALETEQTDE = R.SEQPALETEQTDE AND T.TIPESPECIE = P.TIPESPECIE
AND T.NROEMPRESA = P.NROEMPRESA AND G.SEQPESSOA = T.SEQCLIENTE
AND MP.SEQPRODUTO = P.SEQPRODUTO AND MP.NROEMPRESA = P.CODDEPOSITANTE
AND PE.SEQPRODUTO = P.SEQPRODUTO AND PE.NROEMPRESA = P.CODDEPOSITANTE
AND PE.QTDEMBALAGEM = Q.QTDEMBALAGEM AND A.DTAHORINIMONT >= :DT1
AND A.DTAHORINIMONT < :DT2 + 1 AND A.NROEMPRESA IN (#LS1)
ORDER BY EMPRESA, INICIO_MONTAGEM, ETIQUETA_MASTER, ORDEM_PALETE, ORDEM_VOLUME;
