SELECT DISTINCT
    P.NROEMPRESA AS EMPRESA,
    PI.SEQPRODUTO AS PLU,
    M.DESCCOMPLETA AS DESCRICAO,
    TO_CHAR(:DT1, 'DD/MM/YYYY') AS DIA_CONSULTA,
    TO_CHAR(PI.DTAINICIOPROM, 'DD/MM/YYYY') || ' até ' || 
    TO_CHAR(PI.DTAFIMPROM, 'DD/MM/YYYY') AS PERIODO_PROMO,
    P.PROMOCAO AS NOME_OFERTA,
    TO_CHAR(
        PI.PRECOPROMOCIONAL,
        'FM999G999G990D90',
        'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS PRECO_PROMO,
    TO_CHAR(
        COALESCE(NAG.PRECOPROMOCAO, NAG2.PRECOPROMOCAO),
        'FM999G999G990D90',
        'NLS_NUMERIC_CHARACTERS='',.'''
    ) AS MEUNAGUMO
FROM MRL_PROMOCAOITEM PI
JOIN MRL_PROMOCAO P 
    ON PI.NROEMPRESA   = P.NROEMPRESA
   AND PI.SEQPROMOCAO = P.SEQPROMOCAO
   AND PI.CENTRALLOJA = P.CENTRALLOJA
   AND PI.NROSEGMENTO = P.NROSEGMENTO
JOIN MAP_PRODUTO M 
    ON M.SEQPRODUTO = PI.SEQPRODUTO
LEFT JOIN consinco.NAGV_BASE_PROMOC_PDV_MN NAG
    ON NAG.NROEMPRESA = PI.NROEMPRESA
   AND NAG.SEQPRODUTO = PI.SEQPRODUTO
LEFT JOIN consinco.NAGV_BASE_PROMOC_PDV_MN_SF NAG2
    ON NAG2.NROEMPRESA = PI.NROEMPRESA
   AND NAG2.SEQPRODUTO = PI.SEQPRODUTO
   AND TRUNC(:DT1) BETWEEN TRUNC(NAG2.DTAINICIO) AND TRUNC(NAG2.DTAFIM)
WHERE P.NROEMPRESA IN (#LS1)
  AND NVL(P.TIPOPROMOC, 'N') IN ('N','F','A','S')
  AND PI.QTDEMBALAGEM = 1
  AND TRUNC(:DT1) BETWEEN TRUNC(PI.DTAINICIOPROM) 
                      AND TRUNC(PI.DTAFIMPROM)

UNION ALL

SELECT DISTINCT
    N.NROEMPRESA AS EMPRESA,
    N.SEQPRODUTO AS PLU,
    M.DESCCOMPLETA AS DESCRICAO,
    TO_CHAR(:DT1, 'DD/MM/YYYY') AS DIA_CONSULTA,
    TO_CHAR(N.DTAINICIO, 'DD/MM/YYYY') || ' até ' || TO_CHAR(N.DTAFIM, 'DD/MM/YYYY') AS PERIODO_PROMO,
    NULL AS NOME_OFERTA,
    NULL AS PRECO_PROMO,
    TO_CHAR(N.PRECOPROMOCAO, 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''' ) AS MEUNAGUMO
FROM (
    SELECT
        A.NROEMPRESA,
        A.SEQPRODUTO,
        A.DESCRICAO,
        A.DTAINICIO,
        A.DTAFIM,
        A.PRECOPROMOCAO
    FROM consinco.NAGV_BASE_PROMOC_PDV_MN A
    WHERE TRUNC(:DT1) BETWEEN TRUNC(A.DTAINICIO) AND TRUNC(A.DTAFIM)

    UNION ALL

    SELECT
        A.NROEMPRESA,
        A.SEQPRODUTO,
        A.DESCRICAO,
        A.DTAINICIO,
        A.DTAFIM,
        A.PRECOPROMOCAO
    FROM consinco.NAGV_BASE_PROMOC_PDV_MN_SF A
    WHERE TRUNC(:DT1) BETWEEN TRUNC(A.DTAINICIO) AND TRUNC(A.DTAFIM)
) N
JOIN MAP_PRODUTO M
    ON M.SEQPRODUTO = N.SEQPRODUTO
WHERE N.NROEMPRESA IN (#LS1)
  AND NOT EXISTS (
      SELECT 1
      FROM MRL_PROMOCAOITEM PI2
      WHERE PI2.NROEMPRESA = N.NROEMPRESA
        AND PI2.SEQPRODUTO = N.SEQPRODUTO
        AND TRUNC(:DT1) BETWEEN TRUNC(PI2.DTAINICIOPROM) AND TRUNC(PI2.DTAFIMPROM)
  )
ORDER BY EMPRESA, DESCRICAO;
