-- Solicitação Simone
-- Ticket: 738107
SELECT TO_CHAR(X.LOJA) AS LOJA, TO_CHAR(X.NOTA) AS TITULO, X.FORNECEDOR, TO_CHAR(X.VENCIMENTO_PROGRAMADO, 'DD/MM/YYYY') AS VENCIMENTO_PROGRAMADO, 
X.VALOR_BRUTO, X.VALOR_DESCONTO_CONTRATO, X.VALOR_LIQUIDO, X.OBSERVACAO
FROM (SELECT T.NROEMPRESA AS LOJA, T.NRODOCUMENTO AS NOTA, P.NOMERAZAO AS FORNECEDOR, T.DTAPROGRAMADA AS VENCIMENTO_PROGRAMADO, SUM(T.VLRORIGINAL) AS VALOR_BRUTO,
SUM(NVL(C.VLRDESCCONTRATO, C.VLRDSCFINANC)) AS VALOR_DESCONTO_CONTRATO, SUM(T.VLRNOMINAL) AS VALOR_LIQUIDO,
MAX(T.OBSERVACAO) AS OBSERVACAO, 1 AS ORDEM
FROM CONSINCO.FI_TITULO T
INNER JOIN CONSINCO.GE_PESSOA P ON P.SEQPESSOA = T.SEQPESSOA AND P.VERSAO = T.VERSAOPESSOA
INNER JOIN CONSINCO.FI_COMPLTITULO C ON C.SEQTITULO = T.SEQTITULO
INNER JOIN CONSINCO.FI_AUTPAGTO A ON A.SEQTITULO = T.SEQTITULO
WHERE T.OBRIGDIREITO = 'O' AND T.SITUACAO = 'N' AND T.ABERTOQUITADO = 'A' AND T.CODESPECIE IN (
            'AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
            'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
            'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
            'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
            'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
            'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
            'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
            'SEGURO','SERVPJ','SUPERT','TEL','VLDESC')
AND T.DTAPROGRAMADA >= :DT1
AND T.DTAPROGRAMADA < :DT2 + 1
AND EXISTS (SELECT 1
            FROM CONSINCO.FI_MOVOCOR MO
            WHERE MO.SEQIDENTIFICA = T.SEQTITULO
            AND MO.SEQPESSOA = T.SEQPESSOA
            AND UPPER(MO.OBSERVACAO) LIKE '%REJEITADO PELO BANCO%')
GROUP BY T.NROEMPRESA, T.NRODOCUMENTO, P.NOMERAZAO, T.DTAPROGRAMADA
UNION ALL
SELECT NULL AS LOJA, NULL AS NOTA,
        'TOTAL' AS FORNECEDOR,
        NULL AS VENCIMENTO_PROGRAMADO,
        SUM(T.VLRORIGINAL) AS VALOR_BRUTO,
        SUM(NVL(C.VLRDESCCONTRATO, C.VLRDSCFINANC)) AS VALOR_DESCONTO_CONTRATO,
        SUM(T.VLRNOMINAL) AS VALOR_LIQUIDO,
        NULL AS OBSERVACAO,
        2 AS ORDEM
    FROM CONSINCO.FI_TITULO T
    INNER JOIN CONSINCO.FI_COMPLTITULO C ON C.SEQTITULO = T.SEQTITULO
    INNER JOIN CONSINCO.FI_AUTPAGTO A ON A.SEQTITULO = T.SEQTITULO
    WHERE T.OBRIGDIREITO = 'O'
    AND T.SITUACAO = 'N'
    AND T.ABERTOQUITADO = 'A'
    AND T.CODESPECIE IN ('AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
            'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
            'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
            'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
            'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
            'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
            'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
            'SEGURO','SERVPJ','SUPERT','TEL','VLDESC')
AND T.DTAPROGRAMADA >= :DT1
AND T.DTAPROGRAMADA < :DT2 + 1
AND EXISTS (SELECT 1
            FROM CONSINCO.FI_MOVOCOR MO
            WHERE MO.SEQIDENTIFICA = T.SEQTITULO
            AND MO.SEQPESSOA = T.SEQPESSOA
            AND UPPER(MO.OBSERVACAO) LIKE '%REJEITADO PELO BANCO%')
) X
ORDER BY X.ORDEM, X.LOJA, X.VENCIMENTO_PROGRAMADO, X.FORNECEDOR;
