-- A V2 dessa query foi originalmente feita pelo o Giulis/Biano, mas, o CD pediu 1 milhão de alterações.

SELECT A.NROEMPRESA AS EMPRESA,
CASE WHEN NVL(TRIM(A.CODLINHASEPAR),' ') IN ('EA','EP','S','X',' ') THEN ' - ' ELSE TO_CHAR(W.SEQLOTE) || ' - ' || W.DESCAGRUPAMENTO END AS LOTE,
A.CODLINHASEPAR,L.DESCLINHASEPAR,B.CODEQUIPE,A.NROCARGA,D.DESTINO,B.CODPRODUTIVO,B.NOMEREDUZ AS NOME,
TO_CHAR(A.DTAHORINICIO,'DD/MM/YYYY') AS DTA_INICIO,TO_CHAR(A.DTAHORINICIO,'HH24:MI:SS') AS HOR_INICIO,
TO_CHAR(A.DTAHORFIM,'DD/MM/YYYY') AS DTA_FIM,TO_CHAR(A.DTAHORFIM,'HH24:MI:SS') AS HOR_FIM,
TO_CHAR(TO_DATE('00:00:00','HH24:MI:SS')+NUMTODSINTERVAL(A.TEMPO_MIN,'SECOND'),'HH24:MI:SS') TEMPO_MIN,
A.QTD_ATIVIDADE,A.VOLUME,A.QTD_ITENS,A.PESO,A.CUBAGEM
FROM(
SELECT P.CODLINHASEPAR,P.NROEMPRESA,P.NROCARGA,P.CODPRODUTIVO,
MIN(P.DTAHORINICIO) DTAHORINICIO,
MAX(P.DTAHORFIM) DTAHORFIM,
SUM(NVL(P.TEMPO,0)*60) TEMPO_MIN,
SUM(NVL(P.QTDATIVIDADE,0)) QTD_ATIVIDADE,
SUM(NVL(P.QTDVOLUME,0)) VOLUME,
SUM(NVL(P.QTDITEM,0)) QTD_ITENS,
SUM(NVL(P.PESO,0)) PESO,
SUM(NVL(P.METRAGEMCUBICA,0)) CUBAGEM,
MAX(P.SEQLOTE) SEQLOTE,
MAX(P.NROQUEBRA) NROQUEBRA
FROM CONSINCO.MLO_PRODUTIVIDADE P
LEFT JOIN CONSINCO.MLO_TAREFA T
ON T.SEQTAREFA=P.SEQTAREFA
AND T.MESANO=P.MESANO
AND T.DTAHORFIMTAREFA=P.DTAHORFIM
WHERE TRUNC(NVL(T.DTAHORFIMTAREFA,P.DTAHORFIM)) BETWEEN :DT1 AND :DT2
AND(
P.CODTIPATIVIDADE IN('SS','SE')
OR(
TRIM(P.CODLINHASEPAR) IN('S','X')
AND P.CODTIPATIVIDADE IN('CS','RE','SE','VM')
)
)
AND P.NROEMPRESA IN(502,507,508)
AND P.SEQPRODUTIVIDADEINC IS NULL
AND NOT EXISTS(
SELECT 1
FROM CONSINCO.MLO_PRODUTIVIDADE X
WHERE P.SEQPRODUTIVIDADE=X.SEQPRODUTIVIDADEINC
AND X.NROEMPRESA IN(502,507,508)
)
GROUP BY P.CODLINHASEPAR,P.NROEMPRESA,P.NROCARGA,P.CODPRODUTIVO
) A
LEFT JOIN CONSINCO.MLO_LINHASEPARACAO L
ON TRIM(L.CODLINHASEPAR)=TRIM(A.CODLINHASEPAR)
AND L.NROEMPRESA=A.NROEMPRESA
LEFT JOIN CONSINCO.MLO_PRODUTIVO B
ON B.CODPRODUTIVO=A.CODPRODUTIVO
AND B.NROEMPRESA=A.NROEMPRESA
LEFT JOIN CONSINCO.MLO_CARGAEXPED D
ON D.NROEMPRESA=A.NROEMPRESA
AND D.NROCARGA=A.NROCARGA
LEFT JOIN(
SELECT DISTINCT NROEMPRESA,NROCARGA,SEQLOTE,NROQUEBRA
FROM CONSINCO.MLO_CARREGAMENTOPORPALETELOTE
) CPL
ON CPL.NROEMPRESA=A.NROEMPRESA
AND CPL.NROCARGA=A.NROCARGA
AND CPL.SEQLOTE=A.SEQLOTE
AND NVL(CPL.NROQUEBRA,0)=NVL(A.NROQUEBRA,0)
LEFT JOIN(
SELECT NROEMPRESA,NROCARGA,SEQLOTE,NROQUEBRA,DESCAGRUPAMENTO
FROM(
SELECT W.NROEMPRESA,W.NROCARGA,W.SEQLOTE,W.NROQUEBRA,W.DESCAGRUPAMENTO,
ROW_NUMBER() OVER(
PARTITION BY W.NROEMPRESA,W.NROCARGA,W.SEQLOTE,W.NROQUEBRA
ORDER BY W.DESCAGRUPAMENTO
) RN
FROM CONSINCO.WMSV_CARGAEXPEDLOTES W
)
WHERE RN=1
) W
ON W.NROEMPRESA=CPL.NROEMPRESA
AND W.NROCARGA=CPL.NROCARGA
AND W.SEQLOTE=CPL.SEQLOTE
AND NVL(W.NROQUEBRA,0)=NVL(CPL.NROQUEBRA,0)
WHERE(
NVL(B.CODEQUIPE,0) BETWEEN 1 AND 12
OR NVL(TRIM(A.CODLINHASEPAR),' ') IN('EA','EP','S','X',' ')
OR A.NROEMPRESA=502
)
AND NVL(TRIM(A.CODLINHASEPAR),' ')<>'NC'
ORDER BY A.NROEMPRESA,A.CODLINHASEPAR,B.NOMEREDUZ,A.DTAHORINICIO;
