SELECT T.NROEMPRESA AS LOJA,
       T.SEQPESSOA AS PESSOA,
       P.NOMERAZAO AS NOME_FORNECEDOR,
       T.CODESPECIE AS ESPECIE,
       T.NRODOCUMENTO AS NRO_TITULO,
       TO_CHAR(T.VLRORIGINAL, 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR,
       TO_CHAR(T.DTAEMISSAO, 'DD/MM/YYYY') AS EMISSAO,
       TO_CHAR(N.DTAENTRADA, 'DD/MM/YYYY') AS ENTRADA,
       TO_CHAR(T.DTAVENCIMENTOORIG, 'DD/MM/YYYY') AS VENCIMENTO_ORIGINAL,
       TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS VENCIMENTO_PRORROGADO,
       M.USUALTERACAO AS USUARIO_ALTERACAO,
       TO_CHAR(M.DTAHORA, 'DD/MM/YYYY') AS DTA_ALTERACAO,
       M.OBSERVACAO
  FROM CONSINCO.FI_TITULO T
 INNER JOIN CONSINCO.FI_ESPECIE E
    ON E.CODESPECIE = T.CODESPECIE
   AND E.NROEMPRESAMAE = T.NROEMPRESAMAE
 INNER JOIN CONSINCO.GE_PESSOA P
    ON P.SEQPESSOA = T.SEQPESSOA
  LEFT JOIN CONSINCO.MLF_NOTAFISCAL N
    ON N.NUMERONF = T.NRODOCUMENTO
   AND N.SEQPESSOA = T.SEQPESSOA
   AND N.NROEMPRESA = T.NROEMPRESA
  LEFT JOIN (
        SELECT X.SEQIDENTIFICA,
               X.USUALTERACAO,
               X.DTAHORA,
               X.OBSERVACAO,
               ROW_NUMBER() OVER (
                   PARTITION BY X.SEQIDENTIFICA
                   ORDER BY X.DTAHORA DESC
               ) RN
          FROM CONSINCO.FI_MOVOCOR X
         WHERE X.CODOCORRENCIA = 5
       ) M
    ON M.SEQIDENTIFICA = T.SEQTITULO
   AND M.RN = 1
 WHERE T.CODESPECIE IN (
        SELECT REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL)
        FROM DUAL
        CONNECT BY REGEXP_SUBSTR(:LT1, '[^,]+', 1, LEVEL) IS NOT NULL
       )
   AND TRUNC(T.DTAEMISSAO) BETWEEN :DT1 AND :DT2
   AND NVL(T.DTAVENCIMENTOORIG, T.DTAVENCIMENTO) <> T.DTAVENCIMENTO
 ORDER BY M.USUALTERACAO,
          T.NROEMPRESA,
          T.SEQPESSOA,
          T.DTAEMISSAO,
          T.NRODOCUMENTO;
