-- Ticket: 751997
-- Solicitado por Leticia

SELECT T.EMPRESA, T.ETIQUETA, T.LOJA, TO_CHAR(T.DATA_MONTAGEM, 'DD/MM/YYYY') DATA_MONTAGEM, T.USUARIO,
T.STATUS, T.SEQPRODUTO, X.DESCCOMPLETA,
SUM(NVL(Q.QTDPALETE, 0) + NVL(Q.QTDPALETECANCEL, 0))
/NULLIF(TO_NUMBER(CONSINCO.FC_BUSCADADOSEMBALAGEMEND(T.SEQPRODUTO,MAX(P.CODDEPOSITANTE),SUM(NVL(Q.QTDPALETE, 0) + NVL(Q.QTDPALETECANCEL, 0)),
'Q')),0) QUANTIDADE, CONSINCO.FC_BUSCADADOSEMBALAGEMEND(T.SEQPRODUTO,
MAX(P.CODDEPOSITANTE),SUM(NVL(Q.QTDPALETE, 0) + NVL(Q.QTDPALETECANCEL, 0)),'E') EMBALAGEM, T.LOTE, T.CARGA
FROM CONSINCO.NAGV_ETIQ_WMS T
INNER JOIN CONSINCO.MAP_PRODUTO X ON X.SEQPRODUTO = T.SEQPRODUTO
LEFT JOIN CONSINCO.MLO_PALETEQTDE Q ON Q.SEQPALETECARREG = TO_NUMBER(SUBSTR(TRIM(T.ETIQUETA), 2))
LEFT JOIN CONSINCO.MLO_PALETE P ON P.SEQPALETERF = Q.SEQPALETERF
AND P.SEQPRODUTO = T.SEQPRODUTO
AND P.NROEMPRESA = T.EMPRESA
WHERE T.DATA_MONTAGEM BETWEEN :DT1 AND :DT2
AND T.STATUS IN (#LS1)
AND T.LOJA IN (#LS2)
AND T.EMPRESA IN (#LS3)
AND (Q.SEQPALETERF IS NULL OR P.SEQPALETERF IS NOT NULL)
GROUP BY T.EMPRESA, T.ETIQUETA, T.LOJA, T.DATA_MONTAGEM, T.USUARIO, T.STATUS, T.SEQPRODUTO, X.DESCCOMPLETA, T.LOTE, T.CARGA
ORDER BY X.DESCCOMPLETA;
