-- LITTLE CIGARRO 
-- Minutin?

SELECT 
A.NRO_ACORDO AS NUM_ACORDO,
REGEXP_SUBSTR(A.DESCACORDO, 'SEQ\. LOTE:\s*\d+') AS NUM_LOTE,
R.SEQREDE AS COD_REDE,
R.DESCRICAO AS REDE,
A.COD_FORNECEDOR AS COD_FORNECEDOR,
A.FORNECEDOR AS FORNECEDOR,
TO_CHAR(A.VLR_ACORDO, 'FM999G999G990D00') AS VALOR_ACORDO,
TO_CHAR(V.VALOR_LOTE, 'FM999G999G990D00') AS VALOR_LOTE
FROM CONSINCO.NAGV_TAE_ACORDOS_V4 A
JOIN CONSINCO.MAC_GERCOMPRA G
ON G.SEQGERCOMPRA = REGEXP_SUBSTR(A.DESCACORDO, '\d+$')
JOIN (
SELECT 
SEQGERCOMPRA,
SUM(TFVALORTOTALNF * QTDPEDIDA) AS VALOR_LOTE,
SUM(NVL(VLRUNITVERBA, 0) * QTDPEDIDA) AS VERBA_UNITARIA_TOTAL
FROM CONSINCO.MAC_GERCOMPRAITEM
GROUP BY SEQGERCOMPRA
) V 
ON V.SEQGERCOMPRA = G.SEQGERCOMPRA
JOIN CONSINCO.GE_REDEPESSOA RP 
ON RP.SEQPESSOA = A.COD_FORNECEDOR
JOIN CONSINCO.GE_REDE R 
ON R.SEQREDE = RP.SEQREDE
WHERE A.DESCACORDO LIKE '%SEQ. LOTE:%';
