-- Ticket: 727292
-- Solicitado por: Simone

SELECT
T.NROEMPRESA AS LOJA, T.NRODOCUMENTO AS NOTA,
T.CODESPECIE AS ESPECIE, P.FANTASIA AS FORNECEDOR,
TO_CHAR(T.DTAEMISSAO, 'DD/MM/YYYY') AS EMISSAO, TO_CHAR(A.DTAAUTORIZOU, 'DD/MM/YYYY') AS DATA_AUTORIZACAO, TO_CHAR(T.DTAVENCIMENTO, 'DD/MM/YYYY') AS VENCIMENTO,
TO_CHAR(T.DTAQUITACAO, 'DD/MM/YYYY') AS QUITACAO, T.ABERTOQUITADO, T.VLRORIGINAL AS VALOR_BRUTO, T.VLRNOMINAL AS VALOR_LIQUIDO, A.USUAUTORIZOU AS USUARIO,
(SELECT MAX(MO.OBSERVACAO)
KEEP (DENSE_RANK LAST ORDER BY MO.DTAHORA, MO.SEQMOVOCR)
FROM CONSINCO.FI_MOVOCOR MO
WHERE MO.SEQIDENTIFICA = T.SEQTITULO
AND MO.SEQPESSOA = T.SEQPESSOA AND UPPER(MO.OBSERVACAO) LIKE '%AUTORIZADO PARA PAGAMENTO%') AS OBSERVACAO
FROM CONSINCO.FI_TITULO T
INNER JOIN CONSINCO.GE_PESSOA P ON P.SEQPESSOA = T.SEQPESSOA 
AND P.VERSAO = T.VERSAOPESSOA
INNER JOIN CONSINCO.FI_AUTPAGTO A ON A.SEQTITULO = T.SEQTITULO
WHERE T.SITUACAO = 'N' AND T.OBRIGDIREITO = 'O'
AND T.CODESPECIE IN (
        'AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
        'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
        'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
        'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
        'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
        'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
        'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
        'SEGURO','SERVPJ','SUPERT','TEL','VLDESC')
AND A.DTAAUTORIZOU IS NOT NULL AND (UPPER(A.USUAUTORIZOU) IN (:LS1) OR :LS1 IS NULL) AND TRUNC(A.DTAAUTORIZOU) BETWEEN :DT1 AND :DT2
ORDER BY T.NROEMPRESA, A.DTAAUTORIZOU, T.CODESPECIE;
