SELECT A.NROBOX BOX,
       B.FANTASIA NOME,
       COUNT(DISTINCT A.SEQPALETECARREG) OVER (PARTITION BY A.NROBOX, B.FANTASIA) PALETE,
       CASE 
         WHEN COUNT(DISTINCT A.SEQPALETECARREG) OVER (PARTITION BY A.NROBOX, B.FANTASIA) > 14
         THEN 14 - COUNT(DISTINCT A.SEQPALETECARREG) OVER (PARTITION BY A.NROBOX, B.FANTASIA)
         ELSE 0
       END EXCEDENTE,
       'V' || C.SEQPALETERF || C.SEQPALETEQTDE AS ETIQUETA_LOTE
  FROM CONSINCO.MLO_PALETECARREG A
  JOIN CONSINCO.GE_PESSOA B
    ON A.TIPESPECIE = B.SEQPESSOA
  LEFT JOIN CONSINCO.MLO_PALCARREGRF C
    ON C.SEQPALETECARREG = A.SEQPALETECARREG
 WHERE A.STATUSCARREG = 'M'
   AND A.NROEMPRESA IN (502, 507, 508)
   AND A.NROBOX <> 0
 ORDER BY A.NROBOX, B.FANTASIA
