select 
    A.NROEMPRESA LOJA,
    A.NROTITULO TITULO,
    A.CODESPECIE ESPECIE, 
    A.VLRORIGINAL VALOR_TITULO,
    TO_CHAR(A.DTAMOVIMENTO, 'DD/MM/YYYY') DATA_LANCAMENTO,
    TO_CHAR(B.DTACONTABILIZA, 'DD/MM/YYYY') DATA_CONTABIL,
    TO_CHAR(A.DTAVENCIMENTO, 'DD/MM/YYYY') DATA_VENCIMENTO,
    B.CODOPERACAO OPERACAO,
    B.VLROPERACAO VALOR_OPERACAO,
    TO_CHAR(B.DTAOPERACAO, 'DD/MM/YYYY') DATA_OPERACAO
from consinco.FI_TITULO A
inner join consinco.FI_TITOPERACAO B
    on A.SEQTITULO = B.SEQTITULO 
left join consinco.MRL_TITULOFIN TF
    on TF.SEQTITULO = A.SEQTITULO
left join consinco.MLF_NOTAFISCAL NF
    on NF.SEQAUXNOTAFISCAL = TF.SEQAUXNOTAFISCAL
where B.CODOPERACAO = 141
and TRUNC(A.DTAMOVIMENTO) between :DT1 and :DT2
and A.OBRIGDIREITO = 'O'
and exists (
    select 1
    from consinco.FI_ESPECIE E
    where E.CODESPECIE = A.CODESPECIE
    and E.OBRIGDIREITO = 'O'
    and E.CODESPECIE in (
        'AGUA','ALUGPG','ANTREC','ATIVO','ATIVOC','ATVEFU','BEFUNC',
        'COFINS','COSIND','CSSLL','DESP','DIVSOC','DUPP','DVRBEC',
        'ENERGI','ESPORT','FATDMC','FATCID','FGTS','FGTSQT','FRETE',
        'GNRE','ICMS','IMPOST','INSS','INSSNF','IPI','IPTU','IPVAMU',
        'IR','IRRFFP','IRRNF','ISSQN','ISSQNP','ISST','LEASIM',
        'LEASIN','LEIROU','MKFUNC','MKPREM','PAGEST','PCCNF','PIS',
        'PROCIM','PROCIV','PROTRG','RECARG','REEMB','RETSOC',
        'SEGURO','SERVPJ','SUPERT','TEL','VLDESC'
    )
)
order by A.NROEMPRESA;
